name: Publish package to npmjs

on:
  # workflow_run:
  #   workflows: [Create tag and tarballs release]
  #   types:
  #     - completed
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          registry-url: "https://registry.npmjs.org"

      - run: npm ci

      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
