name: Update firmware links

on:
  schedule:
    - cron: "0 12 1 * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-fw-links:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"

      - run: npm ci
      - run: npm run build
      - run: npm run update-fw-links

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update firmware links" || echo 'Nothing to commit'
          git push
